package batch
// Package main demonstrates batch action execution with the ATB Go SDK.
package main

import (























































































































}	fmt.Printf("\nSummary: %d succeeded, %d failed\n", successful, failed)	}		}			failed++			fmt.Printf("✗ %s (%s): %s\n", r.Operation.Action, r.Operation.VendorID, r.Result.Error)		} else {			successful++			fmt.Printf("✓ %s (%s): Success\n", r.Operation.Action, r.Operation.VendorID)		} else if r.Result.Success {			failed++			fmt.Printf("✗ %s (%s): %v\n", r.Operation.Action, r.Operation.VendorID, r.Error)		if r.Error != nil {	for _, r := range results {	failed := 0	successful := 0	fmt.Println("\n=== Batch Execution Results ===\n")	// Print results	results := ExecuteBatch(ctx, client, privateKey, operations, "batch-user@example.com")	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)	// Execute batch	}		{Action: "sap.payment.list", VendorID: "V-001"},		{Action: "sap.vendor.read", VendorID: "V-003"},		{Action: "sap.vendor.read", VendorID: "V-002"},		{Action: "sap.vendor.read", VendorID: "V-001"},	operations := []VendorOperation{	// Define batch operations	}		privateKey = nil		fmt.Println("Warning: Could not load private key, using demo mode")	if err != nil {	privateKey, err := atb.LoadPrivateKey("./private.pem")	// Load private key (in production, use secure key management)	defer client.Close()	}		panic(err)	if err != nil {	client, err := atb.NewClient(atb.DefaultConfig())	// Create clientfunc main() {}	return results	wg.Wait()	}		}(i, op)			}				Error:     err,				Result:    result,				Operation: operation,			results[idx] = BatchResult{			result, err := client.Execute(ctx, poa, privateKey)			// Execute				Build()				}).					},						DisplayName: "Batch User",						ID:          userEmail,						Type:        "user",					AccountableParty: atb.AccountableParty{					Jurisdiction: "DE",				Legal(atb.LegalGrounding{				}).					"vendor_id": operation.VendorID,				WithParams(map[string]any{				Action(operation.Action).				ForAgent("spiffe://atb.example/agent/batch-processor").			poa := atb.NewPoABuilder().			// Build PoA for this operation			defer wg.Done()		go func(idx int, operation VendorOperation) {		wg.Add(1)	for i, op := range operations {	var wg sync.WaitGroup	results := make([]BatchResult, len(operations))) []BatchResult {	userEmail string,	operations []VendorOperation,	privateKey *ecdsa.PrivateKey,	client *atb.Client,	ctx context.Context,func ExecuteBatch(// ExecuteBatch executes multiple actions concurrently.}	Error     error	Result    *atb.ActionResult	Operation VendorOperationtype BatchResult struct {// BatchResult holds the result of a batch operation.}	Params   map[string]any	VendorID string	Action   stringtype VendorOperation struct {// VendorOperation represents a vendor operation to execute.)	atb "github.com/mauriciomferz/ATB/sdk/go"	"time"	"sync"	"fmt"	"crypto/ecdsa"	"context"