# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM golang:1.25.6 AS build
WORKDIR /src

ARG TARGETOS
ARG TARGETARCH

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath -ldflags="-s -w" -o /out/atb-broker ./cmd/broker

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /
COPY --from=build /out/atb-broker /atb-broker

EXPOSE 8443
EXPOSE 8080

ENTRYPOINT ["/atb-broker"]
