package examples
package main

/*
ATB Client Example - Go









































































































































































































































































































































































}	fmt.Println(repeatStr("=", 60))	fmt.Println("Examples complete!")	fmt.Println("\n" + repeatStr("=", 60))	exampleHighRiskAction(client, privateKey)	exampleMediumRiskAction(client, privateKey)	exampleLowRiskAction(client, privateKey)	}		os.Exit(1)		fmt.Printf("Error creating HTTP client: %v\n", err)	if err != nil {	client, err := createHTTPClient()	// Create HTTP client	}		os.Exit(1)		fmt.Printf("Error loading private key: %v\n", err)	if err != nil {	privateKey, err := loadPrivateKey(poaKeyPath)	// Load private key	}		}			os.Exit(1)			fmt.Println("Run 'make certs && make certs-poa' to generate certificates")			fmt.Printf("\nError: %s not found\n", path)		if _, err := os.Stat(path); os.IsNotExist(err) {	for _, path := range []string{poaKeyPath, clientCertPath, clientKeyPath, caCertPath} {	// Check if files exist	fmt.Printf("Agent SPIFFE ID: %s\n", agentSPIFFEID)	fmt.Printf("Broker URL: %s\n", brokerURL)	fmt.Println("=======================")	fmt.Println("ATB Client Example - Go")func main() {}	return s[:maxLen] + "..."	}		return s	if len(s) <= maxLen {func truncate(s string, maxLen int) string {}	return result	}		result += s	for i := 0; i < n; i++ {	result := ""func repeatStr(s string, n int) string {}	fmt.Printf("Body: %s\n", truncate(string(body), 200))	fmt.Printf("Response: %d\n", resp.StatusCode)	body, _ := io.ReadAll(resp.Body)	defer resp.Body.Close()	}		return		fmt.Printf("Error: %v\n", err)	if err != nil {	resp, err := callBroker(client, "POST", "/sap/payment", token, payload)	}		"currency":  "USD",		"amount":    5000,		"vendor_id": "V12345",	payload := map[string]interface{}{	fmt.Println("Dual Control: approver1@example.com, approver2@example.com")	fmt.Println("Risk Tier: HIGH")	fmt.Println("Action: sap.payment.execute")	}		return		fmt.Printf("Error minting token: %v\n", err)	if err != nil {		legalBasis, 5*time.Minute)		map[string]interface{}{"max_amount": 10000},	token, err := mintPoAToken(privateKey, "sap.payment.execute",	}		},			},				{"id": "approver2@example.com", "timestamp": time.Now().Format(time.RFC3339)},				{"id": "approver1@example.com", "timestamp": time.Now().Format(time.RFC3339)},			"approvers": []map[string]interface{}{		DualControl: map[string]interface{}{		},			"id":   "alice@example.com",			"type": "human",		AccountableParty: map[string]interface{}{		Jurisdiction: "US",		Basis:        "contract",	legalBasis := &LegalBasis{	fmt.Println(repeatStr("=", 60))	fmt.Println("Example 3: High-Risk Action (SAP Payment)")	fmt.Println("\n" + repeatStr("=", 60))func exampleHighRiskAction(client *http.Client, privateKey *rsa.PrivateKey) {}	fmt.Printf("Body: %s\n", truncate(string(body), 200))	fmt.Printf("Response: %d\n", resp.StatusCode)	body, _ := io.ReadAll(resp.Body)	defer resp.Body.Close()	}		return		fmt.Printf("Error: %v\n", err)	if err != nil {	resp, err := callBroker(client, "POST", "/crm/contact", token, payload)	}		"email":      "newemail@example.com",		"contact_id": "C12345",	payload := map[string]interface{}{	fmt.Println("Approval: manager@example.com")	fmt.Println("Risk Tier: MEDIUM")	fmt.Println("Action: crm.contact.update")	}		return		fmt.Printf("Error minting token: %v\n", err)	if err != nil {		legalBasis, 5*time.Minute)		map[string]interface{}{"contact_id": "C12345"},	token, err := mintPoAToken(privateKey, "crm.contact.update",	}		},			"timestamp": time.Now().Format(time.RFC3339),			"approver":  "manager@example.com",		Approval: map[string]interface{}{		},			"id":   "alice@example.com",			"type": "human",		AccountableParty: map[string]interface{}{		Jurisdiction: "US",		Basis:        "contract",	legalBasis := &LegalBasis{	fmt.Println(repeatStr("=", 60))	fmt.Println("Example 2: Medium-Risk Action (CRM Update)")	fmt.Println("\n" + repeatStr("=", 60))func exampleMediumRiskAction(client *http.Client, privateKey *rsa.PrivateKey) {}	fmt.Printf("Body: %s\n", truncate(string(body), 200))	fmt.Printf("Response: %d\n", resp.StatusCode)	body, _ := io.ReadAll(resp.Body)	defer resp.Body.Close()	}		return		fmt.Printf("Error: %v\n", err)	if err != nil {	resp, err := callBroker(client, "GET", "/status", token, nil)	fmt.Printf("PoA Token: %s...\n", token[:50])	fmt.Println("Risk Tier: LOW")	fmt.Println("Action: system.status.read")	}		return		fmt.Printf("Error minting token: %v\n", err)	if err != nil {	token, err := mintPoAToken(privateKey, "system.status.read", nil, nil, 5*time.Minute)	fmt.Println(repeatStr("=", 60))	fmt.Println("Example 1: Low-Risk Action (Status Check)")	fmt.Println("\n" + "=" + repeatStr("=", 59))func exampleLowRiskAction(client *http.Client, privateKey *rsa.PrivateKey) {}	return client.Do(req)	req.Header.Set("X-Request-ID", uuid.New().String())	req.Header.Set("Content-Type", "application/json")	req.Header.Set("Authorization", "Bearer "+poaToken)	}		return nil, fmt.Errorf("failed to create request: %w", err)	if err != nil {	req, err := http.NewRequest(method, url, body)	}		body = bytes.NewReader(data)		}			return nil, fmt.Errorf("failed to marshal payload: %w", err)		if err != nil {		data, err := json.Marshal(payload)	if payload != nil {	var body io.Reader	url := brokerURL + pathfunc callBroker(client *http.Client, method, path, poaToken string, payload interface{}) (*http.Response, error) {// callBroker makes a request to the ATB broker}	}, nil		Timeout: 30 * time.Second,		},			TLSClientConfig: tlsConfig,		Transport: &http.Transport{	return &http.Client{	}		RootCAs:      caCertPool,		Certificates: []tls.Certificate{cert},	tlsConfig := &tls.Config{	}		return nil, fmt.Errorf("failed to add CA certificate to pool")	if !caCertPool.AppendCertsFromPEM(caCert) {	caCertPool := x509.NewCertPool()	}		return nil, fmt.Errorf("failed to read CA certificate: %w", err)	if err != nil {	caCert, err := os.ReadFile(caCertPath)	// Load CA certificate	}		return nil, fmt.Errorf("failed to load client certificate: %w", err)	if err != nil {	cert, err := tls.LoadX509KeyPair(clientCertPath, clientKeyPath)	// Load client certificatefunc createHTTPClient() (*http.Client, error) {// createHTTPClient creates an HTTP client with mTLS}	return token.SignedString(privateKey)	token := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)	}		},			ID:        uuid.New().String(),			ExpiresAt: jwt.NewNumericDate(now.Add(ttl)),			IssuedAt:  jwt.NewNumericDate(now),			Subject:   agentSPIFFEID,		RegisteredClaims: jwt.RegisteredClaims{		Leg: *legalBasis,		Con: constraints,		Act: action,	claims := PoAClaims{	}		constraints = make(map[string]interface{})	if constraints == nil {	}		}			},				"id":   "developer@example.com",				"type": "human",			AccountableParty: map[string]interface{}{			Jurisdiction: "US",			Basis:        "contract",		legalBasis = &LegalBasis{	if legalBasis == nil {	// Default legal basis	now := time.Now()func mintPoAToken(privateKey *rsa.PrivateKey, action string, constraints map[string]interface{}, legalBasis *LegalBasis, ttl time.Duration) (string, error) {// mintPoAToken creates a signed PoA JWT token}	return rsaKey, nil	}		return nil, fmt.Errorf("key is not an RSA private key")	if !ok {	rsaKey, ok := key.(*rsa.PrivateKey)	}		}			return nil, fmt.Errorf("failed to parse private key: %w", err)		if err != nil {		key, err = x509.ParsePKCS1PrivateKey(block.Bytes)		// Try PKCS1 format	if err != nil {	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)	}		return nil, fmt.Errorf("failed to decode PEM block")	if block == nil {	block, _ := pem.Decode(data)	}		return nil, fmt.Errorf("failed to read key file: %w", err)	if err != nil {	data, err := os.ReadFile(path)func loadPrivateKey(path string) (*rsa.PrivateKey, error) {// loadPrivateKey loads an RSA private key from a PEM file}	jwt.RegisteredClaims	Leg LegalBasis             `json:"leg"`	Con map[string]interface{} `json:"con"`	Act string                 `json:"act"`type PoAClaims struct {// PoAClaims represents the claims in a PoA token}	DualControl       map[string]interface{} `json:"dual_control,omitempty"`	Approval          map[string]interface{} `json:"approval,omitempty"`	AccountableParty  map[string]interface{} `json:"accountable_party"`	Jurisdiction      string                 `json:"jurisdiction,omitempty"`	Basis             string                 `json:"basis"`type LegalBasis struct {// LegalBasis represents the legal basis for an action}	return defaultValue	}		return value	if value := os.Getenv(key); value != "" {func getEnv(key, defaultValue string) string {)	agentSPIFFEID = "spiffe://example.org/ns/default/sa/agent/connector"	// SPIFFE ID for this agent	caCertPath     = getEnv("CA_CERT_PATH", "dev/certs/ca.crt")	clientKeyPath  = getEnv("CLIENT_KEY_PATH", "dev/certs/client.key")	clientCertPath = getEnv("CLIENT_CERT_PATH", "dev/certs/client.crt")	poaKeyPath     = getEnv("POA_KEY_PATH", "dev/poa_rsa.key")	brokerURL      = getEnv("ATB_BROKER_URL", "https://localhost:8443")var (// Configuration)	"github.com/google/uuid"	"github.com/golang-jwt/jwt/v5"	"time"	"os"	"net/http"	"io"	"fmt"	"encoding/pem"	"encoding/json"	"crypto/x509"	"crypto/tls"	"crypto/rsa"	"bytes"import (*/    go run examples/client_go.goUsage:3. Call the ATB broker with mTLS + PoA2. Mint a PoA token1. Load SPIFFE client certificatesThis example demonstrates how to: